spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3307/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://127.0.0.1:3308/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: read_only_user
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver