server:
  port: 8080

# 需要使用 redis 的话，放开这里
spring:
  redis:
    host: 127.0.0.1
    database: 0

security:
  oauth2:
    resource:
      filter-order: 3

aiqiyi.redirect.url: http://localhost:8080/aiqiyi/qq/redirect
youku.redirect.url: http://localhost:8080/youku/qq/redirect
project.host: http://localhost:8080
oauth.url: ${project.host}/oauth/authorize
aiqiyi.client.id: aiqiyi
youku.client.id: youku
aiqiyi.client.secret: aqy_secret
youku.client.secret: yk_secret
logging.level.org.springframework.security: DEBUG